### ISSUE TITLE
Im getting `self is not defined` error.

### ISSUE THREAD

**Issue by loq24** [treyhuffine/lightbox-react#8]
Any advise on how to fix this? Thanks

**Comment by treyhuffine** [comment]
I haven't experienced this error myself @loq24. Do you have an example that's causing it?

**Comment by ewallkrishnaprakash** [comment]
@treyhuffine I am also getting this issue on SSR (Server side rendering).

**Comment by treyhuffine** [comment]
I'm unsure on how to reproduce :(

There are checks to make sure window/navigator are defined before using them

**Comment by Tseberechts** [comment]
I'm getting the same error when testing. 

1. Create a new create-react-app project
2. replace app.js by the example in the lightbox-react readme
3. `yarn test`

![screen shot 2018-05-28 at 17 27 37](https://user-images.githubusercontent.com/18442053/40621291-794d0a1e-629c-11e8-82dd-3b00e0fcdd44.png)

**Comment by axeff** [comment]
Same here. Basic example. Installed via yarn.

**Comment by axeff** [comment]
In my case it could be due to server side rendering, where of course window is not existing.
When I render the page without lightbox and inject it afterwards it is working.

**Comment by treyhuffine** [comment]
Thanks for the update everyone 😄Looks like an easy case to reproduce @Tseberechts, let me look into it.

**Comment by kokno** [comment]
@axeff what are you using to inject lightbox after rendering ?

**Comment by axeff** [comment]
Only webpack. I'll let the page load/render without lightbox and then edit my component afterwards so that the hot module replacement updates only the needed components without reloading the whole page from backend.
And I use next.js for server side rendering.

**Comment by ewief** [comment]
updating style-loader package will fix this error.

**Comment by treyhuffine** [comment]
Hey everyone sorry for the delay, this should be fixed now. I didn't actually expect other people to use this package when I added it, but I'll try to be better about supporting it moving forward.

Going to close this for now but let me know if you see any other issues.

**Comment by treyhuffine** [comment]
Also, add `import 'lightbox-react/style.css';` to your project now. The style has been decouple from the functionality.
