### ISSUE TITLE
Incorrect Peer Dependencies

### ISSUE THREAD

**Issue by rmincling** [treyhuffine/lightbox-react#9]
Hi,

I've upgraded to react 16.4 which now causes "incorrect peer dependency" warnings with this package (see below). Just wondering if this package is still being maintained or if anyone can give advice how to correct these issues?

> warning " > lightbox-react@0.1.6" has incorrect peer dependency "react@^15.0.0".
warning " > lightbox-react@0.1.6" has incorrect peer dependency "react-dom@^15.0.0".
warning "lightbox-react > react-modal@1.9.7" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning "lightbox-react > react-modal@1.9.7" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0".

Cheers

**Comment by treyhuffine** [comment]
Hey @rmincling sorry for the delay, this should be fixed now. I didn't actually expect other people to use this package when I added it, but I'll try to be better about supporting it moving forward.

Going to close this for now but feel free to reopen if you still see any issues.

**Comment by rmincling** [comment]
Hi Trey,

Thank you for the update, those warnings now disappear. However, now the compoent doesn't seem to work, it appears the styles are not working.  When I click on an image to activate the lightbox I notice the following (Chrome):

1. No black background
2. The full size image is not loaded
3. The title/captions are not in the correct places

When I go back to the previous version of lightbox-react all is fine again. Not sure what is going on.

Regards

**Comment by treyhuffine** [comment]
@rmincling add `import 'lightbox-react/style.css';` to your project. The style has been decoupled from the functionality.

**Comment by rmincling** [comment]
That did the trick, thank you!, Great job bud! I like that this package can handle both image and video objects too. Keep up the good work!

**Comment by treyhuffine** [comment]
I appreciate the kind words, that's exactly why I made it :) - I just didn't realize other people would actually find it and use it haha.
